spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/F1}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: true
  flyway:
    enabled: true
    locations: classpath:db
    validate-on-migrate: true
    default-schema: public

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN